### ISSUE TITLE
Adding @gibfahn to help repo / perhaps give collaborators group access

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/CTC#58]
I'm making this issue to document manually adding @gibfahn to the help repo as a collaborator. There are two other individuals who have manually been given these permissions as well.

I would like to suggest that we give collaborator permission to @nodejs/collaborators, allowing people to opt out of notifications but maintain the ability to admin the repo.

Thoughts?

**Comment by gibfahn** [comment]
More people looking at nodejs/help seems like a good idea to me.

**Comment by jasnell** [comment]
has this been done yet?

**Comment by gibfahn** [comment]
I don't think so, looking at https://github.com/orgs/nodejs/teams/collaborators/repositories

_**EDIT:**_ I do now have edit access to this repo, although I can't work out how. The giving nodejs/Collaborators permissions in nodejs/help is what is outstanding.

**Comment by targos** [comment]
The "Adding @gibfahn to help repo" part happened.
@gibfahn you have been given individual access from https://github.com/nodejs/help/settings/collaboration

I am really +1 on adding `nodejs/collaborators` to the allowed teams. Currently, only `nodejs/evangelism` is there.
Do we need a formal approval from @nodejs/ctc ?

**Comment by Trott** [comment]
> Do we need a formal approval from @nodejs/ctc ?

Since we don't have (AFAIK) a documented process for adding people to the help repo, I'd say no, it doesn't *need* formal approval. But some consensus-seeking seems in order.

I'd propose:

* tag @nodejs/ctc for comments (oh look at that, already done)
* mention it at the CTC meeting that's happening in about 14 hours

If no one objects in either place&mdash;that is, if we only have expressions of support along perhaps with some expressions of indifference&mdash;that seems to me a reasonable indicator that we have consensus on adding nodejs/collaborators team to the nodejs/help repo.

**Comment by gibfahn** [comment]
>The "Adding @gibfahn to help repo" part happened.
@gibfahn you have been given individual access from https://github.com/nodejs/help/settings/collaboration

Ahh okay, I can't see that page (I assume you have to be a `nodejs` org owner to see it).

**Comment by addaleax** [comment]
Reading through this thread it looks like we have consensus that this is a good idea, and I don’t think there’s much harm in giving the collaborator group write access. Done!
